# Generated by Django 4.0.4 on 2022-04-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idea',
            table='idea',
        ),
    ]
