# Generated by Django 4.0.4 on 2022-05-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_idea_author_alter_idea_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('Jogos', 'Jogos'), ('Educativo', 'Educativos'), ('Entretenimento', 'Entretenimento'), ('Saúde e bem-estar', 'Saude'), ('Aleatorio', 'Aleatorio')], default='Outros', max_length=20),
        ),
    ]
